import {
  mdiRobotAngry,
  mdiAccountGroup,
  mdiPlus,
  mdiMagnify,
  mdiAccount,
  mdiChevronRight,
  mdiChevronDown,
  mdiArrowRight,
  mdiCheck,
  mdiTranslate,
  mdiStar,
  mdiSortAlphabeticalAscending,
  mdiContentCopy,
  mdiPound,
  mdiViewList,
} from "@mdi/js";

export default {
  mdiRobotAngry,
  mdiAccountGroup,
  mdiPlus,
  mdiMagnify,
  mdiAccount,
  mdiChevronRight,
  mdiChevronDown,
  mdiArrowRight,
  mdiCheck,
  mdiTranslate,
  mdiStar,
  mdiSortAlphabeticalAscending,
  mdiContentCopy,
  mdiPound,
  mdiViewList,
};
